
function plotMap( regionColor, mapBoundaries, plotTitle)
%generates a map of the given region using the given colors
% Inputs:regionColor is a structure array that contains the color of each
%                    region/subregion.
%        mapBoundaries is the structure array generated by
%                    the provided function getBoundaryDataFromFile.m
%        plotTitle is a string for the map's title
% Returns: creates a plot


hold(gca,'on');
x = []; y = [];
regionNames = {regionColor.regionName};
for i=1:length(mapBoundaries)
    x =  mapBoundaries(i).latitude ;
    y =  mapBoundaries(i).longitude ;
    regionName = mapBoundaries(i).regionName;
    indexOfRegion = find(ismember(regionNames, mapBoundaries(i).regionName));
    
    if (~isempty(indexOfRegion))
        color = regionColor(indexOfRegion).color;
        fill(y,x, color);
    end
end

title(plotTitle);
axis equal;

end

